name: pandas_workshop
channels:
    - conda-forge
dependencies:
    - python>=3.9.0,<=3.12.30
    - jupyterlab>=4.2.3
    - matplotlib=3.8.4
    - numpy=2.0.0
    - pandas=2.2.2
    - requests
    - seaborn=0.13.2
